import { z } from 'zod';
import {
  VALIDATION_CONSTRAINTS,
  VALIDATION_PATTERNS,
  VALIDATION_MESSAGES,
  FORM_FIELD_NAMES,
} from '../../../shared/constants/appConstants';

export const loginSchema = z.object({
  usernameOrEmail: z
    .string()
    .min(1, VALIDATION_MESSAGES.USERNAME_OR_EMAIL_REQUIRED)
    .min(VALIDATION_CONSTRAINTS.USERNAME.MIN_LENGTH, VALIDATION_MESSAGES.USERNAME_LENGTH)
    .max(VALIDATION_CONSTRAINTS.USERNAME.MAX_LENGTH, VALIDATION_MESSAGES.USERNAME_LENGTH),
  password: z.string().min(1, VALIDATION_MESSAGES.PASSWORD_REQUIRED),
});

export const registerSchema = z
  .object({
    username: z
      .string()
      .min(1, VALIDATION_MESSAGES.USERNAME_REQUIRED)
      .min(VALIDATION_CONSTRAINTS.USERNAME.MIN_LENGTH, VALIDATION_MESSAGES.USERNAME_LENGTH)
      .max(VALIDATION_CONSTRAINTS.USERNAME.MAX_LENGTH, VALIDATION_MESSAGES.USERNAME_LENGTH)
      .regex(VALIDATION_PATTERNS.USERNAME, VALIDATION_MESSAGES.USERNAME_FORMAT),
    email: z
      .string()
      .min(1, VALIDATION_MESSAGES.EMAIL_REQUIRED)
      .email(VALIDATION_MESSAGES.EMAIL_INVALID)
      .max(VALIDATION_CONSTRAINTS.EMAIL.MAX_LENGTH, VALIDATION_MESSAGES.EMAIL_LENGTH_MAX),
    password: z
      .string()
      .min(VALIDATION_CONSTRAINTS.PASSWORD.MIN_LENGTH, VALIDATION_MESSAGES.PASSWORD_LENGTH_MIN)
      .max(VALIDATION_CONSTRAINTS.PASSWORD.MAX_LENGTH, VALIDATION_MESSAGES.PASSWORD_LENGTH_MAX)
      .regex(VALIDATION_PATTERNS.PASSWORD_UPPERCASE, VALIDATION_MESSAGES.PASSWORD_UPPERCASE)
      .regex(VALIDATION_PATTERNS.PASSWORD_LOWERCASE, VALIDATION_MESSAGES.PASSWORD_LOWERCASE)
      .regex(VALIDATION_PATTERNS.PASSWORD_NUMBER, VALIDATION_MESSAGES.PASSWORD_NUMBER)
      .regex(VALIDATION_PATTERNS.PASSWORD_SPECIAL, VALIDATION_MESSAGES.PASSWORD_SPECIAL),
    confirmPassword: z.string().min(1, VALIDATION_MESSAGES.CONFIRM_PASSWORD_REQUIRED),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: VALIDATION_MESSAGES.PASSWORDS_DO_NOT_MATCH,
    path: [FORM_FIELD_NAMES.CONFIRM_PASSWORD],
  });

export const forgotPasswordSchema = z.object({
  email: z
    .string()
    .min(1, VALIDATION_MESSAGES.EMAIL_REQUIRED)
    .email(VALIDATION_MESSAGES.EMAIL_INVALID)
    .min(VALIDATION_CONSTRAINTS.EMAIL.MIN_LENGTH, VALIDATION_MESSAGES.EMAIL_LENGTH_MIN)
    .max(VALIDATION_CONSTRAINTS.EMAIL.MAX_LENGTH, VALIDATION_MESSAGES.EMAIL_LENGTH_MAX),
});

export const resetPasswordSchema = z.object({
  newPassword: z.string()
    .min(VALIDATION_CONSTRAINTS.PASSWORD.MIN_LENGTH, VALIDATION_MESSAGES.PASSWORD_LENGTH_MIN)
    .max(VALIDATION_CONSTRAINTS.PASSWORD.MAX_LENGTH, VALIDATION_MESSAGES.PASSWORD_LENGTH_MAX)
    .regex(VALIDATION_PATTERNS.PASSWORD_UPPERCASE, VALIDATION_MESSAGES.PASSWORD_UPPERCASE)
    .regex(VALIDATION_PATTERNS.PASSWORD_LOWERCASE, VALIDATION_MESSAGES.PASSWORD_LOWERCASE)
    .regex(VALIDATION_PATTERNS.PASSWORD_NUMBER, VALIDATION_MESSAGES.PASSWORD_NUMBER)
    .regex(VALIDATION_PATTERNS.PASSWORD_SPECIAL, VALIDATION_MESSAGES.PASSWORD_SPECIAL),
  confirmPassword: z.string()
    .min(1, VALIDATION_MESSAGES.CONFIRM_PASSWORD_REQUIRED),
}).refine((data) => data.newPassword === data.confirmPassword, {
  message: VALIDATION_MESSAGES.PASSWORDS_DO_NOT_MATCH,
  path: [FORM_FIELD_NAMES.CONFIRM_PASSWORD],
});

export type LoginSchemaType = z.infer<typeof loginSchema>;
export type RegisterSchemaType = z.infer<typeof registerSchema>;
export type ForgotPasswordSchemaType = z.infer<typeof forgotPasswordSchema>;
export type ResetPasswordSchemaType = z.infer<typeof resetPasswordSchema>;

export type LoginSchema = LoginSchemaType;
export type RegisterSchema = RegisterSchemaType;
export type ForgotPasswordSchema = ForgotPasswordSchemaType;
export type ResetPasswordSchema = ResetPasswordSchemaType;


